import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { FaRobot } from "react-icons/fa"
import { ChevronLeft, ChevronRight } from 'lucide-react'
import { Button } from "@/components/ui/button"

const aiGens = [
  { name: "Udio", description: "Experience music generated by Udio AI, blending creativity and technology." },
  { name: "Suno", description: "Create original music with Suno AI, pushing the boundaries of AI-generated audio." },
  { name: "Mureka", description: "Dive into melodies crafted by Mureka, your AI-powered music companion." },
  { name: "Sonauto", description: "Explore innovative soundscapes with Sonauto's cutting-edge AI music generation." },
]

export function AIRecommendations() {
  const [currentIndex, setCurrentIndex] = useState(0)

  const nextRecommendation = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 2) % aiGens.length)
  }

  const prevRecommendation = () => {
    setCurrentIndex((prevIndex) => (prevIndex - 2 + aiGens.length) % aiGens.length)
  }

  return (
    <Card className="my-6">
      <CardHeader>
        <CardTitle>Recommend AI Music Gens ♫</CardTitle>
      </CardHeader>
      <CardContent className="flex items-center justify-between">
        <Button variant="ghost" onClick={prevRecommendation}>
          <ChevronLeft className="h-6 w-6" />
        </Button>
        <div className="grid grid-cols-2 gap-4 flex-grow">
          {aiGens.slice(currentIndex, currentIndex + 2).map((gen) => (
            <Card key={gen.name} className="flex items-center space-x-4 p-4">
              <FaRobot className="h-8 w-8 text-primary" />
              <div>
                <h3 className="font-bold">{gen.name}</h3>
                <p className="text-sm text-muted-foreground">{gen.description}</p>
              </div>
            </Card>
          ))}
        </div>
        <Button variant="ghost" onClick={nextRecommendation}>
          <ChevronRight className="h-6 w-6" />
        </Button>
      </CardContent>
    </Card>
  )
}

